name: "Docker Build Action"
description: "Custom action to build Docker images"
author: "Your Name"
 
inputs:
  image_name:
    description: "Name of the Docker image"
    required: true
  context:
    description: "Docker build context"
    default: "."
 
runs:
  using: "docker"
  image: "Dockerfile"
