name: Test Docker Build Action
 
on:
  workflow_dispatch:
 
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
 
      - name: Run Docker Build Action
        uses: ./
        with:
          image_name: my-custom-nginx
          context: .
